.github/workflows/pull-request.yaml
kubectl-plugin/auth/common.go
kubectl-plugin/component/component.go
kubectl-plugin/component/reset.go
kubectl-plugin/registry/root.go
kubectl-plugin/update.go

The usage like: `kubectl ks com reset -a --nightly latest`

Add support reset components to nightly

---

.github/.typo-ci.yml
kubectl-plugin/cmd.go
kubectl-plugin/component/reset.go
kubectl-plugin/install/kind.go
kubectl-plugin/install/root.go

Add support to install ks in kind

---

.goreleaser.yml
README.md
kubectl-plugin/entrypoint/cmd.go
kubectl-plugin/kubectl-ks.go
kubectl-plugin/pipeline/root.go
kubectl-plugin/update/root.go
main.go

This will be a much simple way to manipulate the KubeSphere cluster

Mix kubectl-ks and kubectl alias into one

---

kubectl-plugin/common/net.go
kubectl-plugin/install/installer.go
kubectl-plugin/install/k3d.go
kubectl-plugin/install/root.go

fix #108
The usage is: `ks install k3d`

Add support to intall KubeSphere with k3d

---

README.md

Fix the ks install instructions

---

kubectl-plugin/config/config_root.go
kubectl-plugin/config/migrate.go
kubectl-plugin/config/types.go

Usage:
```
ks option migrate --service ks-ctl-ks-devops-apiserver.kubesphere-devops-system
```

Add devops migrate command

---

.github/workflows/pull-request.yaml
.github/workflows/release.yaml
go.mod
go.sum
kubectl-plugin/install/containerd/config.toml
kubectl-plugin/install/containerd/containerd.service
kubectl-plugin/install/containerd/crictl.yaml
kubectl-plugin/install/containerd/kk_config.yaml
kubectl-plugin/install/containerd/resource.go
kubectl-plugin/install/containerd/resource_test.go
kubectl-plugin/install/kind.go
kubectl-plugin/install/kk.go
kubectl-plugin/install/kk_test.go

upstream https://github.com/LinuxSuRen/http-downloader/pull/99

Add containerd config files

---

kubectl-plugin/install/kind.go

1. fix kind version argument invalid
2. fix ksVersion argument invalid
3. fix kind cluster name argument invalid
test result:

fix install kind argument invalid

---

kubectl-plugin/install/installer.go
kubectl-plugin/install/k3d.go

Usage: `ks install k3d --with-ks=false --reinstall=true`

Support to install k3d without KubeSphere

---

kubectl-plugin/pipeline/create.go
kubectl-plugin/pipeline/run.go
kubectl-plugin/pipeline/tpl/parameter.groovy
kubectl-plugin/pipeline/tpl/resource.go
kubectl-plugin/pipeline/tpl/resource_test.go
kubectl-plugin/pipeline/tpl/simple.groovy

- Support trigger a pipelinerun via project name
- Add very simple jenkinsfile template

support project pipelinerun

---

kubectl-plugin/pipeline/run.go
kubectl-plugin/types/schema.go

See the reason from https://github.com/kubesphere/ks-devops/pull/238

Change the version of PipelineRun to v1alpha3

---

go.mod
go.sum
kubectl-plugin/common/client.go
kubectl-plugin/pipeline/dashboard.go
kubectl-plugin/pipeline/root.go
kubectl-plugin/pipeline/run.go

Usage: `ks pip dash`
Screenshot:

Add a dashboard for pipelines

---

kubectl-plugin/install/kk.go
kubectl-plugin/types/constant.go

Usage: `ks install kk --components devops --kubernetesVersion v1.22.1 --version v3.2.0`

Add a flag kubernetes version to kk install

---

codecov.yml

this is inspired from https://github.com/kubesphere/ks-devops/blob/master/codecov.yml

Add config file of codecov

---

.github/tekton/README.md
.github/tekton/gateway.yaml
.github/tekton/ingress.yaml
.github/tekton/trigger-eventlistener.yaml

Signed-off-by: John Niang <johnniang@fastmail.com>

Add gateway and ingress manifests

---

.github/tekton/trigger-eventlistener.yaml

Signed-off-by: John Niang <johnniang@fastmail.com>

Fix typo of build-bot

---

docs/app.md
go.mod
go.sum
kubectl-plugin/app/client.go
kubectl-plugin/app/root.go
kubectl-plugin/app/update.go
kubectl-plugin/app/update_test.go
kubectl-plugin/common/exec.go
kubectl-plugin/entrypoint/cmd.go
kubectl-plugin/types/schema.go

related PRs https://github.com/kubesphere-sigs/ks-devops-helm-chart/pull/61

Support to update argo cd application

---

kubectl-plugin/app/update.go
kubectl-plugin/app/update_test.go

see the [changes](https://github.com/kubesphere/ks-devops/pull/502/files?diff=split&w=0#diff-882117145d3c095f99af6fce79d454d9beba9ee3050f81720803928b647c0937L30)

Fix the application spec path

---

README.md

Adds a simple recording on how to use ks to install kubesphere and tail logs.
kubectl commands included to show status of resources.
solves #230

Add recording for basic usage

---

.gitignore
kubectl-plugin/pipeline/dashboard.go
kubectl-plugin/pipeline/gc.go
kubectl-plugin/pipeline/gc_test.go
kubectl-plugin/pipeline/option/create.go

1. fix bug of global gc-pipelinerun
2. add feature of gc-pipelinerun of each pipeline

bugfix of gc-pipeline

---

kubectl-plugin/pipeline/gc.go
kubectl-plugin/pipeline/gc_test.go
kubectl-plugin/pipeline/option/create.go

- update: only gc pipelinerun of pipeline that the type is NoSCMPipelineType

bugfix gc pipeline

---

kubectl-plugin/pipeline/gc.go
kubectl-plugin/pipeline/option/create.go
kubectl-plugin/pipeline/ui/project/form.go

- bugfix: 
contentKey spec.multi_branch_pipeline
permission-denied of logfile & log to stdout
clean pipelinerun twice
- update
output by logrus in gc-pipeline
add field id to gcPipelinerun

Bugfix: gc-pipelinerun

---

.github/workflows/release.yaml

update github-action release

---

kubectl-plugin/pipeline/gc.go

fix kubesphere/ks-devops#737
- disable gc pipelineruns in projects by default
- fix: gc pipelineruns by pipeline discarder

fix issue-737 in ks-devops

---

.github/workflows/release.yaml
.goreleaser.yml

- update param of releaser to --clean
- remove replacements in goreleaser.yaml

update goreleaser: remove replacements

---

go.mod
go.sum
kubectl-plugin/app/update.go

- create branch per condition (https://github.com/kubesphere/project/issues/5494)
- add author info when committing (https://github.com/kubesphere/project/issues/5494)
- support specifying author email
- upgrade to go 1.18

fix `ks app update` command
